# Databricks notebook source
# MAGIC %md
# MAGIC # Impact of Hits: Insights & Visualizations
# MAGIC Combines the estimated state-space model with auxiliary models to generate insights and plots.
# MAGIC
# MAGIC Generates 7 visualizations:
# MAGIC   1. Model Summary Stats Table
# MAGIC   2. Single-Game Momentum Timeline (smoothed vs observed)
# MAGIC   3. B Coefficients (all events)
# MAGIC   4. Impulse Response Decay Curves
# MAGIC   5. Hit Impact by Ice Zone (for vs against)
# MAGIC   6. Team Momentum Scatter (hits per game vs avg momentum)
# MAGIC   7. Expected Goals Probability Surface

ENV = "LOCAL"

# COMMAND ----------
# MAGIC %load_ext autoreload
# MAGIC %autoreload 2

import sys
import os
import torch
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for saving
import matplotlib.pyplot as plt

try:
    # Local Python execution
    current_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
    if parent_dir not in sys.path:
        sys.path.append(parent_dir)
except NameError:
    # Databricks execution (no __file__ defined)
    parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
    if parent_dir not in sys.path:
        sys.path.append(parent_dir)

data_dir = os.path.join(parent_dir, 'data')
os.makedirs(data_dir, exist_ok=True)

from src.model.estimation import fit_ssm, bootstrap_B
from src.model.inference import compute_half_life
from src.model.smoother import extract_smoothed_states
from src.analysis.aux_goal_model import fit_expected_goals_model
from src.viz.plotting import (
    plot_model_summary_table,
    plot_game_momentum_timeline,
    plot_B_coefficients,
    plot_impulse_response,
    plot_hit_impact_by_zone,
    plot_team_momentum_scatter,
    plot_expected_goals_surface,
)

# COMMAND ----------
# MAGIC %md
# MAGIC ### 1. Dataset & Model Loading
# MAGIC We assume `games` and `base_model` have been generated by Notebook 02.

# COMMAND ----------
if ENV == "LOCAL":
    df_master = pd.read_parquet(os.path.join(data_dir, "df_master.parquet"))
    base_model = torch.load(os.path.join(data_dir, "base_model.pt"), weights_only=False)
    B_samples = np.load(os.path.join(data_dir, "B_samples.npy"))
else:
    from pyspark.sql import SparkSession
    spark = SparkSession.builder.getOrCreate()
    df_master = spark.table("`nhl-databricks`.compute.impact_of_hits_master").toPandas()
    # Loading model in Databricks typically from DBFS or MLflow
    # base_model = torch.load("/dbfs/mnt/models/base_model.pt")
    # B_samples = np.load("/dbfs/mnt/models/B_samples.npy")

event_cols = [
    "hit_for_O", "hit_for_D", "hit_for_N", "hit_against_O", "hit_against_D", "hit_against_N",
    "shot_for", "shot_against",
    "takeaway", "giveaway", "block_for", "block_against", "faceoff_win"
]
baseline_cols = ["is_home", "focal_delta_pythagorean", "focal_delta_CF_pct", "score_state"]

# Precompute stats
B_hat = base_model.B.detach().numpy()
B_lo = np.percentile(B_samples, 2.5, axis=0)
B_hi = np.percentile(B_samples, 97.5, axis=0)
a0_hat = torch.sigmoid(base_model.log_a0).item()
half_life = compute_half_life(a0_hat)

# Reconstruct game tensor dicts (needed for smoother)
games = []
for game_id, group in df_master.groupby("game_id"):
    U = torch.tensor(group[event_cols].values, dtype=torch.float32)
    Y = torch.tensor(group["rolling_zone_share_90s"].values, dtype=torch.float32)
    Z = torch.tensor(group[baseline_cols].values, dtype=torch.float32)
    dt = torch.tensor(np.diff(group["elapsed_sec"].values, prepend=0.0), dtype=torch.float32)
    games.append({"game_id": game_id, "U": U, "Y": Y, "Z": Z, "dt": dt})

print(f"Loaded model and {len(games)} games. a0={a0_hat:.5f}, half-life={half_life:.1f}s")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 1: Model Summary Stats Table

# COMMAND ----------
print("Generating Viz 1: Model Summary Stats Table...")
fig1 = plot_model_summary_table(B_hat, B_lo, B_hi, event_cols, a0_hat, half_life)
fig1.savefig(os.path.join(data_dir, "viz1_summary_table.png"), dpi=150, bbox_inches='tight')
plt.close(fig1)
print("  ✓ Saved viz1_summary_table.png")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 2: Single-Game Momentum Timeline
# MAGIC Run the Kalman smoother to extract latent momentum, then plot a representative game.

# COMMAND ----------
print("Running Kalman smoother on all games...")
smoothed_results = extract_smoothed_states(base_model, games)
print(f"  Smoothed {len(smoothed_results)} games.")

# Pick a representative game (the one with most events for visual richness)
longest_idx = max(range(len(smoothed_results)), key=lambda i: len(smoothed_results[i]["x_smooth"]))
fig2 = plot_game_momentum_timeline(smoothed_results[longest_idx])
fig2.savefig(os.path.join(data_dir, "viz2_momentum_timeline.png"), dpi=150, bbox_inches='tight')
plt.close(fig2)
print("  ✓ Saved viz2_momentum_timeline.png")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 3: B Coefficients (all events)

# COMMAND ----------
print("Generating Viz 3: B Coefficients...")
fig3 = plot_B_coefficients(B_hat, B_lo, B_hi, event_cols)
fig3.savefig(os.path.join(data_dir, "viz3_coefficients.png"), dpi=150, bbox_inches='tight')
plt.close(fig3)
print("  ✓ Saved viz3_coefficients.png")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 4: Impulse Response Decay Curves

# COMMAND ----------
print("Generating Viz 4: Impulse Response...")
hit_b = B_hat[event_cols.index("hit_for_O")]
takeaway_b = B_hat[event_cols.index("takeaway")]
shot_b = B_hat[event_cols.index("shot_for")]
fig4 = plot_impulse_response(
    a0_val=a0_hat,
    b_vals={"Hit (O-Zone)": hit_b, "Takeaway": takeaway_b, "Shot On Goal": shot_b},
    max_sec=180
)
fig4.savefig(os.path.join(data_dir, "viz4_impulse_response.png"), dpi=150, bbox_inches='tight')
plt.close(fig4)
print("  ✓ Saved viz4_impulse_response.png")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 5: Hit Impact by Ice Zone (FOR vs AGAINST)

# COMMAND ----------
print("Generating Viz 5: Hit Impact by Ice Zone...")
fig5 = plot_hit_impact_by_zone(B_hat, B_lo, B_hi, event_cols)
fig5.savefig(os.path.join(data_dir, "viz5_hit_impact.png"), dpi=150, bbox_inches='tight')
plt.close(fig5)
print("  ✓ Saved viz5_hit_impact.png")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 6: Team Momentum Scatter
# MAGIC Aggregate per-team: average smoothed momentum and hits per game.

# COMMAND ----------
print("Generating Viz 6: Team Momentum Scatter...")

# Build a team-level summary from smoothed results and raw data
team_stats = []
for res in smoothed_results:
    gid = res["game_id"]
    game_rows = df_master[df_master["game_id"] == gid]
    if len(game_rows) == 0:
        continue
    team = game_rows["focal_team_abbrev"].iloc[0]
    total_hits = game_rows[["hit_for_O", "hit_for_D", "hit_for_N"]].sum().sum()
    avg_mom = float(np.mean(res["x_smooth"]))
    team_stats.append({"focal_team_abbrev": team, "hits": total_hits, "avg_momentum": avg_mom})

df_team_agg = pd.DataFrame(team_stats).groupby("focal_team_abbrev").agg(
    total_hits=("hits", "sum"),
    total_games=("hits", "count"),
    avg_momentum=("avg_momentum", "mean"),
).reset_index()
df_team_agg["hits_per_game"] = df_team_agg["total_hits"] / df_team_agg["total_games"]

fig6 = plot_team_momentum_scatter(df_team_agg)
fig6.savefig(os.path.join(data_dir, "viz6_team_scatter.png"), dpi=150, bbox_inches='tight')
plt.close(fig6)
print("  ✓ Saved viz6_team_scatter.png")

# COMMAND ----------
# MAGIC %md
# MAGIC ### Viz 7: Expected Goals Probability Surface

# COMMAND ----------
print("Generating Viz 7: Expected Goals Surface...")
goal_model = fit_expected_goals_model(smoothed_results)
fig7 = plot_expected_goals_surface(goal_model)
fig7.savefig(os.path.join(data_dir, "viz7_expected_goals.png"), dpi=150, bbox_inches='tight')
plt.close(fig7)
print("  ✓ Saved viz7_expected_goals.png")

# COMMAND ----------
print("\n" + "=" * 60)
print("Pipeline complete! All 7 visualizations saved to:")
print(f"  {data_dir}")
print("=" * 60)
