name: NHL API pull data for game-level stats (games and odds)

on:
  schedule:
    # This runs the workflow daily at 20:00 UTC, which is 3 PM CT during Daylight Saving Time
    # Only in hockey season months (January to June and October to December)
    - cron: '0 20 * 1-6,10-12 *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    environment: data-collection

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements/requirements.txt

    - name: Run NHL Game Record Data
      run: python src/data/apinhle/data_pull_box.py

    - name: Run NHL Odds Data
      run: python src/data/apinhle/data_pull_box_odds.py

    - name: Run NHL Game-level Summary to Game Records and Season-team Statistics
      if: always()
      run: python src/data/apinhle/data_proc_gameSummary.py

    - name: Run NHL Game-level Play-by-play record data
      if: always()
      run: python src/data/apinhle/data_pull_plays.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add latest/box/*.csv
        git add latest/team/season/*.csv
        git add latest/play/*.csv 
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m 'Automated data update'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
