name: NHL API pull for odds data

on:
  schedule:
    - cron: '0 20 * * *'  # This runs the workflow daily at 20:00 UTC, which is 3 PM CT during Daylight Saving Time
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.12.2'  # Specify the Python version you need
        channels: conda-forge,defaults  # Add conda-forge and defaults channels

    - name: Create environment and install dependencies
      run: |
        conda create --name myenv --yes
        echo "source activate myenv" >> $GITHUB_ENV
        conda activate myenv
        # Install dependencies using conda if available, otherwise use pip
        while read requirement; do
          conda install --yes $requirement || pip install $requirement;
        done < src/requirements.txt

    - name: Run Python script
      run: python src/data/apinhle/data_pull_odds.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add src/path/to/latest/*.csv
        git commit -m 'Automated data update'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
